# Generated by Django 2.0.2 on 2018-02-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_mvc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='storage/'),
        ),
        migrations.AlterField(
            model_name='reputation',
            name='reputee_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_mvc.Author'),
        ),
        migrations.AlterField(
            model_name='reputation',
            name='reputee_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_mvc.Post'),
        ),
    ]
