# Generated by Django 2.0.2 on 2018-02-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_mvc', '0002_auto_20180227_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contributions',
            field=models.DecimalField(decimal_places=27, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='post',
            name='contributors',
            field=models.IntegerField(default=0),
        ),
    ]
